import 'package:flutter/material.dart';
import 'package:dinar_watch/theme/theme_manager.dart';

class ColorSchemeManager {
  static final ThemeData darkTheme = ThemeManager.baseTheme(
    ColorScheme.fromSeed(
      seedColor: Colors.transparent,
      brightness: Brightness.dark,
      primary:const  Color(0xFFCFBCFF),
      onPrimary: const Color(0xFF381E72),
      primaryContainer: const Color(0xFF4F378A),
      onPrimaryContainer: const Color(0xFFE9DDFF),
      secondary: const Color(0xFFCBC2DB),
      onSecondary: const Color(0xFF332D41),
      secondaryContainer: const Color(0xFF4A4458),
      onSecondaryContainer: const Color(0xFFE8DEF8),
      tertiary: const Color(0xFFEFB8C8),
      onTertiary: const Color(0xFF4A2532),
      tertiaryContainer: const Color(0xFF633B48),
      onTertiaryContainer: const Color(0xFFFFD9E3),
      error: const Color(0xFFFFB4AB),
      errorContainer: const Color(0xFF93000A),
      onError: const Color(0xFF690005),
      onErrorContainer: const Color(0xFFFFDAD6),
      background: const Color(0xFF1C1B1E),
      onBackground: const Color(0xFFE6E1E6),
      surface: const Color(0xFF1C1B1E),
      onSurface: const Color(0xFFE6E1E6),
      surfaceVariant: const Color(0xFF49454E),
      onSurfaceVariant: const Color(0xFFCAC4CF),
      outline: const Color(0xFF948F99),
      onInverseSurface: const Color(0xFF1C1B1E),
      inverseSurface: const Color(0xFFE6E1E6),
      inversePrimary: const Color(0xFF6750A4),
      shadow: const Color(0xFF000000),
      surfaceTint: const Color(0xFFCFBCFF),
      outlineVariant: const Color(0xFF49454E),
      scrim: const Color(0xFF000000),
    ),
  );

  static ThemeData lightTheme = ThemeManager.baseTheme(
    ColorScheme.fromSeed(
      seedColor: Colors.transparent,
      brightness: Brightness.light,
      primary: const Color(0xFF6750A4),
      onPrimary: const Color(0xFFFFFFFF),
      primaryContainer:const Color(0xFFE9DDFF),
      onPrimaryContainer:const Color(0xFF22005D),
      secondary:const Color(0xFF625B71),
      onSecondary:const Color(0xFFFFFFFF),
      secondaryContainer:const Color(0xFFE8DEF8),
      onSecondaryContainer:const Color(0xFF1E192B),
      tertiary:const Color(0xFF7E5260),
      onTertiary:const Color(0xFFFFFFFF),
      tertiaryContainer:const Color(0xFFFFD9E3),
      onTertiaryContainer:const Color(0xFF31101D),
      error:const Color(0xFFBA1A1A),
      errorContainer:const Color(0xFFFFDAD6),
      onError:const Color(0xFFFFFFFF),
      onErrorContainer:const Color(0xFF410002),
      background:const Color(0xFFFFFBFF),
      onBackground:const Color(0xFF1C1B1E),
      surface:const Color(0xFFFFFBFF),
      onSurface:const Color(0xFF1C1B1E),
      surfaceVariant:const Color(0xFFE7E0EB),
      onSurfaceVariant:const Color(0xFF49454E),
      outline:const Color(0xFF7A757F),
      onInverseSurface:const Color(0xFFF4EFF4),
      inverseSurface:const Color(0xFF313033),
      inversePrimary:const Color(0xFFCFBCFF),
      shadow:const Color(0xFF000000),
      surfaceTint:const Color(0xFF6750A4),
      outlineVariant:const Color(0xFFCAC4CF),
      scrim:const Color(0xFF000000),
    ),
  );
}
