name: dinar_watch
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.13.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  http: ^1.1.0
  logger: ^2.0.2+1
  fl_chart: ^0.65.0
  google_fonts: ^6.1.0
  firebase_app_check: ^0.2.1+4
  firebase_auth: ^4.14.0
  decimal: ^2.3.3
  cached_network_image: ^3.3.0
  animations: ^2.0.10
  firebase_core: ^2.24.2
  flutter_native_splash: ^2.3.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/dz.png
    - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo2.png
  color_dark: "#000000"
  image_dark: assets/logo.png
