name: Build Flutter Bundle

on:
  push:
    branches:
      - main

env:
  SIGNING_KEY_PATH: ${{ github.workspace }}/release.keystore

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Decode Keystore File
      run: |
              echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > $SIGNING_KEY_PATH
              ls -l $SIGNING_KEY_PATH  # Check the decoded file

    - name: Extract Version from pubspec.yaml
      id: get_version
      run: |
        VERSION_LINE=$(grep 'version:' pubspec.yaml)
        VERSION_BASE=$(echo $VERSION_LINE | cut -d '+' -f 1 | awk '{print $2}')
        echo "VERSION_BASE=$VERSION_BASE" >> $GITHUB_ENV

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'  
        channel: stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Set executable permissions for build.sh
      run: chmod +x ./build.sh

    - name: Run custom build script
      run: ./build.sh
      shell: bash

    - name: Export Environment Variables for Signing
      run: |
        echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
        echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
        echo "SIGNING_KEY_STORE_PASSWORD=${{ secrets.SIGNING_KEY_STORE_PASSWORD }}" >> $GITHUB_ENV
        echo "SIGNING_KEY_PATH=${{ env.SIGNING_KEY_PATH }}" >> $GITHUB_ENV

    - name: Build App Bundle
      run: flutter build appbundle --release --build-name=$VERSION_BASE --build-number=${{ github.run_number }}

    - name: Upload App Bundle
      uses: actions/upload-artifact@v3
      with:
        name: release-bundle
        path: build/app/outputs/bundle/release/app-release.aab

    - name: Upload App Bundle to Google Play
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.GPLAY_SERVICE_ACCOUNT }}
        packageName: com.dinarexchange.app
        releaseFiles: build/app/outputs/bundle/release/app-release.aab
        track: DinarEchangeClosed

