name: Build Flutter APK

on:
  push:
    branches:
      - main  # Set this to the branch where you want the action to trigger
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # Since building an APK does not require macOS and is less costly

    steps:
    - name: Clone repository
      uses: actions/checkout@v4

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.6'  
        channel: stable

    - name: Install Dependencies
      run: flutter pub get

    - name: Set executable permissions for build.sh
      run: chmod +x ./build.sh

    - name: Run custom build script
      run: ./build.sh
      shell: bash

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk

