name: Build Flutter Bundle

on:
  push:
    tags:
      - 'release-*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java and Flutter
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
        
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'
          channel: stable

      - name: Install Dependencies and Setup Build Environment
        run: |
          flutter pub get
          chmod +x ./unix_build.sh
          echo "Extracting version..."
          VERSION_LINE=$(grep 'version:' pubspec.yaml)
          VERSION_BASE=$(echo $VERSION_LINE | cut -d '+' -f 1 | awk '{print $2}')
          echo "VERSION_BASE=$VERSION_BASE" >> $GITHUB_ENV
          echo "Configuring signing..."
          echo "SIGNING_KEY_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}" >> $GITHUB_ENV
          echo "SIGNING_KEY_STORE_PASSWORD=${{ secrets.SIGNING_KEY_STORE_PASSWORD }}" >> $GITHUB_ENV

      - name: Build and Bundle
        run: |
          ./unix_build.sh
          flutter build appbundle --release --build-name=$VERSION_BASE --build-number=${{ github.run_number }}

      - name: Distribute
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/release-')
        run: |
          mkdir -p upload_payload
          mv build/app/outputs/bundle/release/app-release.aab upload_payload/app-release.aab
          echo 'Uploading to Google Play...'

      - uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GPLAY_SERVICE_ACCOUNT }}
          packageName: com.dinarexchange.app
          releaseFiles: upload_payload/app-release.aab
          track: DinarEchangeClosed
