name: Validate Keystore Configuration

on:
  workflow_dispatch:

jobs:
  verify-keystore:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Decode Keystore File
      run: |
        echo "${{ secrets.KEYSTORE_FILE }}" | base64 --decode > ${{ github.workspace }}/release.keystore
        echo "Keystore decoded to ${{ github.workspace }}/release.keystore"

    - name: Verify Keystore
      run: |
        keytool -list -keystore ${{ github.workspace }}/release.keystore -alias ${{ secrets.SIGNING_KEY_ALIAS }} -storepass ${{ secrets.SIGNING_KEY_STORE_PASSWORD }} -keypass ${{ secrets.SIGNING_KEY_PASSWORD }} -v
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_KEY_STORE_PASSWORD: ${{ secrets.SIGNING_KEY_STORE_PASSWORD }}

    - name: Display Keystore Path
      run: echo "Keystore is located at ${{ github.workspace }}/release.keystore"
